import json

nb = json.load(open('D:/pelanca/training/pelanca_nnue_v3_kaggle.ipynb'))

# Cell 1: Add numba import
nb['cells'][1]['source'] = [
"!pip install python-chess -q 2>/dev/null\n",
"!pip install h5py tqdm -q 2>/dev/null\n",
"\n",
"import chess\n",
"import torch\n",
"import torch.nn as nn\n",
"import torch.nn.functional as F\n",
"import torch.optim as optim\n",
"from torch.utils.data import Dataset, DataLoader\n",
"import numpy as np\n",
"import pandas as pd\n",
"import h5py\n",
"import struct\n",
"import os\n",
"import time\n",
"from tqdm.auto import tqdm\n",
"from numba import njit, prange\n",
"\n",
"print(f'PyTorch {torch.__version__} | CUDA {torch.cuda.is_available()}')\n",
"if torch.cuda.is_available():\n",
"    for i in range(torch.cuda.device_count()):\n",
"        print(f'  GPU {i}: {torch.cuda.get_device_name(i)}')"
]

# Cell 6: Dataset + numba-accelerated make_batches
nb['cells'][6]['source'] = [
"_PIECE_MAP = {\n",
"    'P': (0, 0), 'N': (0, 1), 'B': (0, 2), 'R': (0, 3), 'Q': (0, 4), 'K': (0, 5),\n",
"    'p': (1, 0), 'n': (1, 1), 'b': (1, 2), 'r': (1, 3), 'q': (1, 4), 'k': (1, 5),\n",
"}\n",
"\n",
"def fen_to_sparse_fast(fen_str):\n",
"    if isinstance(fen_str, bytes): fen_str = fen_str.decode()\n",
"    parts = fen_str.split(' ')\n",
"    stm = 0 if parts[1] == 'w' else 1\n",
"    wi, bi = [], []\n",
"    sq = 56\n",
"    for ch in parts[0]:\n",
"        if ch == '/': sq -= 16\n",
"        elif ch.isdigit(): sq += int(ch)\n",
"        else:\n",
"            color, pt = _PIECE_MAP[ch]\n",
"            wi.append(color * 384 + pt * 64 + sq)\n",
"            bi.append((1 - color) * 384 + pt * 64 + (sq ^ 56))\n",
"            sq += 1\n",
"    return stm, wi, bi\n",
"\n",
"\n",
"PREPROCESSED_FILE = HDF5_FILE.replace('.h5', '_preprocessed.h5')\n",
"\n",
"def preprocess_split(h5_src, h5_dst, split, max_pos=None):\n",
"    import gc\n",
"    with h5py.File(h5_src, 'r') as f:\n",
"        total = len(f[split]['evals'])\n",
"        n = min(total, max_pos) if max_pos else total\n",
"        evals = f[split]['evals'][:n].astype(np.float32)\n",
"    print(f'[{split}] Pre-processando {n:,} FENs...')\n",
"    max_pieces = n * 32\n",
"    w_flat = np.empty(max_pieces, dtype=np.int16)\n",
"    b_flat = np.empty(max_pieces, dtype=np.int16)\n",
"    offsets = np.empty(n + 1, dtype=np.int32)\n",
"    stm = np.empty(n, dtype=np.uint8)\n",
"    CHUNK = 500_000\n",
"    pos = 0\n",
"    offsets[0] = 0\n",
"    for cs in tqdm(range(0, n, CHUNK), desc=f'  {split}', total=(n+CHUNK-1)//CHUNK):\n",
"        ce = min(cs + CHUNK, n)\n",
"        with h5py.File(h5_src, 'r') as f:\n",
"            fc = f[split]['fens'][cs:ce]\n",
"        for j, rf in enumerate(fc):\n",
"            i = cs + j\n",
"            s, wi, bi = fen_to_sparse_fast(rf)\n",
"            k = len(wi)\n",
"            w_flat[pos:pos+k] = wi\n",
"            b_flat[pos:pos+k] = bi\n",
"            pos += k\n",
"            offsets[i+1] = pos\n",
"            stm[i] = s\n",
"        del fc\n",
"        gc.collect()\n",
"    w_flat = w_flat[:pos]\n",
"    b_flat = b_flat[:pos]\n",
"    with h5py.File(h5_dst, 'a') as f:\n",
"        g = f.require_group(split)\n",
"        for name, arr in [('w_flat', w_flat), ('b_flat', b_flat),\n",
"                          ('offsets', offsets), ('stm', stm), ('evals', evals)]:\n",
"            if name in g: del g[name]\n",
"            g.create_dataset(name, data=arr)\n",
"    mb = (w_flat.nbytes+b_flat.nbytes+offsets.nbytes+evals.nbytes+stm.nbytes)/1e6\n",
"    print(f'  Salvo: {mb:.0f} MB')\n",
"    del w_flat, b_flat, offsets, stm, evals\n",
"    gc.collect()\n",
"\n",
"if os.path.exists(PREPROCESSED_FILE):\n",
"    with h5py.File(PREPROCESSED_FILE, 'r') as f:\n",
"        if 'train' in f and 'w_flat' in f['train']:\n",
"            print(f'Pre-processado existe: {PREPROCESSED_FILE}')\n",
"        else:\n",
"            preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'train')\n",
"            preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'val', max_pos=500_000)\n",
"else:\n",
"    preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'train')\n",
"    preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'val', max_pos=500_000)\n",
"\n",
"\n",
"class NnueSparseDatasetV3(Dataset):\n",
"    def __init__(self, h5_path, split='train', mirror=False):\n",
"        self.mirror = mirror\n",
"        t0 = time.time()\n",
"        with h5py.File(h5_path, 'r') as f:\n",
"            g = f[split]\n",
"            self.w_flat = g['w_flat'][:]\n",
"            self.b_flat = g['b_flat'][:]\n",
"            self.offsets = g['offsets'][:].astype(np.int64)\n",
"            self.stm = g['stm'][:]\n",
"            self.evals = g['evals'][:]\n",
"        self.n = len(self.evals)\n",
"        elapsed = time.time() - t0\n",
"        mb = (self.w_flat.nbytes+self.b_flat.nbytes+self.offsets.nbytes+self.evals.nbytes+self.stm.nbytes)/1e6\n",
"        print(f'[{split}] {self.n:,} em {elapsed:.1f}s ({mb:.0f} MB)' + (f' (x2={self.n*2:,})' if mirror else ''))\n",
"\n",
"    def __len__(self): return self.n * 2 if self.mirror else self.n\n",
"\n",
"\n",
"# ============================================================\n",
"# NUMBA: batch builder compilado para codigo nativo\n",
"# Zero np.repeat, 1 loop paralelo, ~10x mais rapido que numpy\n",
"# ============================================================\n",
"\n",
"@njit(cache=True)\n",
"def _batch_offsets(offsets_arr, batch_idx, n, mirror):\n",
"    B = len(batch_idx)\n",
"    lengths = np.empty(B, dtype=np.int64)\n",
"    batch_off = np.empty(B, dtype=np.int64)\n",
"    for i in range(B):\n",
"        idx = batch_idx[i]\n",
"        ri = idx - n if (mirror and idx >= n) else idx\n",
"        lengths[i] = offsets_arr[ri + 1] - offsets_arr[ri]\n",
"    total = np.int64(0)\n",
"    for i in range(B):\n",
"        batch_off[i] = total\n",
"        total += lengths[i]\n",
"    return lengths, batch_off, total\n",
"\n",
"\n",
"@njit(parallel=True, cache=True)\n",
"def _fill_batch(w_flat, b_flat, offsets_arr, stm, evals,\n",
"                batch_idx, n, mirror,\n",
"                lengths, batch_off,\n",
"                out_w, out_b, out_ev):\n",
"    B = len(batch_idx)\n",
"    for i in prange(B):\n",
"        idx = batch_idx[i]\n",
"        is_mirror = mirror and (idx >= n)\n",
"        ri = idx - n if is_mirror else idx\n",
"        start = offsets_arr[ri]\n",
"        out_pos = batch_off[i]\n",
"        length = lengths[i]\n",
"        is_black = stm[ri] == 1\n",
"        for j in range(length):\n",
"            w = np.int64(w_flat[start + j])\n",
"            b = np.int64(b_flat[start + j])\n",
"            if is_mirror:\n",
"                w ^= 7\n",
"                b ^= 7\n",
"            if is_black:\n",
"                w, b = b, w\n",
"            out_w[out_pos + j] = w\n",
"            out_b[out_pos + j] = b\n",
"        ev = evals[ri]\n",
"        if is_black:\n",
"            ev = -ev\n",
"        out_ev[i] = ev\n",
"\n",
"\n",
"def make_batches(ds, batch_size, shuffle=True):\n",
"    n = len(ds)\n",
"    perm = np.random.permutation(n).astype(np.int64) if shuffle else np.arange(n, dtype=np.int64)\n",
"    max_total = batch_size * 32\n",
"    out_w = np.empty(max_total, dtype=np.int64)\n",
"    out_b = np.empty(max_total, dtype=np.int64)\n",
"    out_ev = np.empty(batch_size, dtype=np.float32)\n",
"    mirror = ds.mirror\n",
"    for bs in range(0, n - batch_size + 1, batch_size):\n",
"        batch_idx = perm[bs:bs + batch_size]\n",
"        B = len(batch_idx)\n",
"        lengths, batch_off, total = _batch_offsets(ds.offsets, batch_idx, np.int64(ds.n), mirror)\n",
"        if total > len(out_w):\n",
"            out_w = np.empty(total, dtype=np.int64)\n",
"            out_b = np.empty(total, dtype=np.int64)\n",
"        _fill_batch(ds.w_flat, ds.b_flat, ds.offsets, ds.stm, ds.evals,\n",
"                    batch_idx, np.int64(ds.n), mirror,\n",
"                    lengths, batch_off, out_w, out_b, out_ev)\n",
"        yield (\n",
"            torch.from_numpy(out_w[:total].copy()),\n",
"            torch.from_numpy(batch_off),\n",
"            torch.from_numpy(out_b[:total].copy()),\n",
"            torch.from_numpy(batch_off.copy()),\n",
"            torch.from_numpy(out_ev[:B].copy()),\n",
"        )\n",
"\n",
"\n",
"# Warmup numba (JIT compila na primeira chamada, ~5s)\n",
"print('Compilando numba...', end=' ', flush=True)\n",
"_dummy_off = np.array([0, 2, 5], dtype=np.int64)\n",
"_dummy_idx = np.array([0, 1], dtype=np.int64)\n",
"_dummy_w = np.array([1,2,3,4,5], dtype=np.int16)\n",
"_dummy_b = np.array([6,7,8,9,10], dtype=np.int16)\n",
"_dummy_stm = np.array([0, 1], dtype=np.uint8)\n",
"_dummy_ev = np.array([0.5, -0.3], dtype=np.float32)\n",
"_l, _bo, _t = _batch_offsets(_dummy_off, _dummy_idx, np.int64(2), False)\n",
"_ow = np.empty(5, dtype=np.int64)\n",
"_ob = np.empty(5, dtype=np.int64)\n",
"_oe = np.empty(2, dtype=np.float32)\n",
"_fill_batch(_dummy_w, _dummy_b, _dummy_off, _dummy_stm, _dummy_ev,\n",
"            _dummy_idx, np.int64(2), False, _l, _bo, _ow, _ob, _oe)\n",
"print('OK')"
]

json.dump(nb, open('D:/pelanca/training/pelanca_nnue_v3_kaggle.ipynb', 'w'), indent=1)
print('Notebook v3c salvo com numba!')
