import json

nb = json.load(open('D:/pelanca/training/pelanca_nnue_v3_kaggle.ipynb'))

# Cell 5: mudar titulo
nb['cells'][5]['source'] = ["---\n", "## Pre-processar FENs -> arrays binarios (1x) + Dataset (instantaneo)"]

# Cell 6: Pre-processamento + Dataset que carrega instantaneo
nb['cells'][6]['source'] = [
"_PIECE_MAP = {\n",
"    'P': (0, 0), 'N': (0, 1), 'B': (0, 2), 'R': (0, 3), 'Q': (0, 4), 'K': (0, 5),\n",
"    'p': (1, 0), 'n': (1, 1), 'b': (1, 2), 'r': (1, 3), 'q': (1, 4), 'k': (1, 5),\n",
"}\n",
"\n",
"def fen_to_sparse_fast(fen_str):\n",
"    if isinstance(fen_str, bytes): fen_str = fen_str.decode()\n",
"    parts = fen_str.split(' ')\n",
"    stm = 0 if parts[1] == 'w' else 1\n",
"    wi, bi = [], []\n",
"    sq = 56\n",
"    for ch in parts[0]:\n",
"        if ch == '/': sq -= 16\n",
"        elif ch.isdigit(): sq += int(ch)\n",
"        else:\n",
"            color, pt = _PIECE_MAP[ch]\n",
"            wi.append(color * 384 + pt * 64 + sq)\n",
"            bi.append((1 - color) * 384 + pt * 64 + (sq ^ 56))\n",
"            sq += 1\n",
"    return stm, wi, bi\n",
"\n",
"\n",
"PREPROCESSED_FILE = HDF5_FILE.replace('.h5', '_preprocessed.h5')\n",
"\n",
"def preprocess_split(h5_src, h5_dst, split, max_pos=None):\n",
"    \"\"\"Converte FENs -> w_flat/b_flat/offsets/stm e salva no HDF5.\n",
"    Roda 1x. Depois o Dataset carrega em 2 segundos.\"\"\"\n",
"    import gc\n",
"    with h5py.File(h5_src, 'r') as f:\n",
"        total = len(f[split]['evals'])\n",
"        n = min(total, max_pos) if max_pos else total\n",
"        evals = f[split]['evals'][:n].astype(np.float32)\n",
"\n",
"    print(f'[{split}] Pre-processando {n:,} FENs...')\n",
"\n",
"    max_pieces = n * 32\n",
"    w_flat = np.empty(max_pieces, dtype=np.int16)\n",
"    b_flat = np.empty(max_pieces, dtype=np.int16)\n",
"    offsets = np.empty(n + 1, dtype=np.int32)\n",
"    stm = np.empty(n, dtype=np.uint8)\n",
"\n",
"    CHUNK = 500_000\n",
"    pos = 0\n",
"    offsets[0] = 0\n",
"\n",
"    for cs in tqdm(range(0, n, CHUNK), desc=f'  {split}', total=(n + CHUNK - 1) // CHUNK):\n",
"        ce = min(cs + CHUNK, n)\n",
"        with h5py.File(h5_src, 'r') as f:\n",
"            fens_chunk = f[split]['fens'][cs:ce]\n",
"        for j, raw_fen in enumerate(fens_chunk):\n",
"            i = cs + j\n",
"            s, wi, bi = fen_to_sparse_fast(raw_fen)\n",
"            k = len(wi)\n",
"            w_flat[pos:pos + k] = wi\n",
"            b_flat[pos:pos + k] = bi\n",
"            pos += k\n",
"            offsets[i + 1] = pos\n",
"            stm[i] = s\n",
"        del fens_chunk\n",
"        gc.collect()\n",
"\n",
"    w_flat = w_flat[:pos]\n",
"    b_flat = b_flat[:pos]\n",
"\n",
"    # Salvar no HDF5 pre-processado\n",
"    with h5py.File(h5_dst, 'a') as f:\n",
"        g = f.require_group(split)\n",
"        for name, arr in [('w_flat', w_flat), ('b_flat', b_flat),\n",
"                          ('offsets', offsets), ('stm', stm), ('evals', evals)]:\n",
"            if name in g: del g[name]\n",
"            g.create_dataset(name, data=arr)\n",
"\n",
"    mb = (w_flat.nbytes + b_flat.nbytes + offsets.nbytes + evals.nbytes + stm.nbytes) / 1e6\n",
"    print(f'  Salvo: {mb:.0f} MB | {pos / n:.1f} pecas/pos')\n",
"    del w_flat, b_flat, offsets, stm, evals\n",
"    gc.collect()\n",
"\n",
"\n",
"# Pre-processar se necessario (1x, depois e instantaneo)\n",
"if os.path.exists(PREPROCESSED_FILE):\n",
"    with h5py.File(PREPROCESSED_FILE, 'r') as f:\n",
"        if 'train' in f and 'w_flat' in f['train']:\n",
"            print(f'Pre-processado existe: {PREPROCESSED_FILE}')\n",
"        else:\n",
"            preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'train')\n",
"            preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'val', max_pos=500_000)\n",
"else:\n",
"    preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'train')\n",
"    preprocess_split(HDF5_FILE, PREPROCESSED_FILE, 'val', max_pos=500_000)\n",
"\n",
"\n",
"class NnueSparseDatasetV3(Dataset):\n",
"    \"\"\"Carrega arrays pre-processados do HDF5. Instantaneo (~2s).\"\"\"\n",
"\n",
"    def __init__(self, h5_path, split='train', mirror=False):\n",
"        self.mirror = mirror\n",
"        t0 = time.time()\n",
"        with h5py.File(h5_path, 'r') as f:\n",
"            g = f[split]\n",
"            self.w_flat = g['w_flat'][:]\n",
"            self.b_flat = g['b_flat'][:]\n",
"            self.offsets = g['offsets'][:]\n",
"            self.stm = g['stm'][:]\n",
"            self.evals = g['evals'][:]\n",
"        self.n = len(self.evals)\n",
"        elapsed = time.time() - t0\n",
"        mb = (self.w_flat.nbytes + self.b_flat.nbytes + self.offsets.nbytes +\n",
"              self.evals.nbytes + self.stm.nbytes) / 1e6\n",
"        print(f'[{split}] {self.n:,} pos em {elapsed:.1f}s ({mb:.0f} MB)' +\n",
"              (f' (x2={self.n*2:,})' if mirror else ''))\n",
"\n",
"    def __len__(self):\n",
"        return self.n * 2 if self.mirror else self.n\n",
"\n",
"\n",
"def make_batches(ds, batch_size, shuffle=True):\n",
"    n = len(ds)\n",
"    perm = np.random.permutation(n) if shuffle else np.arange(n)\n",
"    for bs in range(0, n - batch_size + 1, batch_size):\n",
"        idx = perm[bs:bs + batch_size]\n",
"        mm = idx >= ds.n\n",
"        ri = np.where(mm, idx - ds.n, idx)\n",
"        B = len(idx)\n",
"        starts = ds.offsets[ri].astype(np.int64)\n",
"        ends = ds.offsets[ri + 1].astype(np.int64)\n",
"        lengths = ends - starts\n",
"        cl = np.cumsum(lengths)\n",
"        bo = np.empty(B, dtype=np.int64)\n",
"        bo[0] = 0\n",
"        bo[1:] = cl[:-1]\n",
"        total = int(cl[-1])\n",
"        base = np.repeat(starts, lengths)\n",
"        within = np.arange(total, dtype=np.int64) - np.repeat(bo, lengths)\n",
"        flat = base + within\n",
"        aw = ds.w_flat[flat].astype(np.int64)\n",
"        ab = ds.b_flat[flat].astype(np.int64)\n",
"        if ds.mirror and mm.any():\n",
"            me = np.repeat(mm, lengths)\n",
"            aw[me] ^= 7\n",
"            ab[me] ^= 7\n",
"        blk = ds.stm[ri] == 1\n",
"        evs = ds.evals[ri].copy()\n",
"        evs[blk] *= -1\n",
"        if blk.any():\n",
"            be = np.repeat(blk, lengths)\n",
"            tmp = aw[be].copy()\n",
"            aw[be] = ab[be]\n",
"            ab[be] = tmp\n",
"        yield (torch.from_numpy(aw), torch.from_numpy(bo),\n",
"               torch.from_numpy(ab), torch.from_numpy(bo.copy()),\n",
"               torch.from_numpy(evs))\n",
"\n",
"\n",
"print('OK')"
]

# Cell 12: Load dataset (agora instantaneo)
nb['cells'][12]['source'] = [
"import gc; gc.collect()\n",
"print('Carregando arrays pre-processados...\\n')\n",
"\n",
"train_ds = NnueSparseDatasetV3(PREPROCESSED_FILE, 'train', mirror=MIRROR_AUG)\n",
"val_ds = NnueSparseDatasetV3(PREPROCESSED_FILE, 'val')\n",
"gc.collect()\n",
"\n",
"VAL_BATCH = min(BATCH_SIZE, len(val_ds))\n",
"effective = len(train_ds)\n",
"n_batches = effective // BATCH_SIZE\n",
"print(f'\\nTrain: {n_batches} batches x {BATCH_SIZE:,} ({effective:,} eff)')\n",
"print(f'Gradient steps total: {n_batches * EPOCHS:,}')"
]

json.dump(nb, open('D:/pelanca/training/pelanca_nnue_v3_kaggle.ipynb', 'w'), indent=1)
print('Notebook v3b salvo com pre-processamento!')
